[package]
name = "percy"
version = "0.1.0"
authors = ["Bradlee Speice <bradlee@speice.io>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
percy-webapis = "0.0.1"
virtual-dom-rs = "0.1"
wasm-bindgen = "0.2"
