[package]
name = "web-view_wasm"
version = "0.1.0"
authors = ["Bradlee Speice <bradlee@speice.io>"]

[dependencies]
app = { path = "./app" }
lazy_static = "1.1"
percy-webapis = "0.0.1"
virtual-dom-rs = "0.1"
web-view = "0.2"
