[package]
name = "electron_yew_wasm"
version = "0.1.0"
authors = ["Bradlee Speice <bradlee@speice.io>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
stdweb = "0.4"
wasm-bindgen = "0.2"
yew = { git = "https://github.com/DenisKolodin/yew" }